-- ======================================================================
-- แปลงความลึกของเข็มเป็น cun ตามตำรา — สิบเส้นที่เหลือ
-- LU LI SP HT SI KI PC TH LIV CV รวม 177 จุด
--
-- ที่มา: Xie's Veterinary Acupuncture (2007) บทที่ 5 หัวข้อ METHOD
--
-- ส่วนที่ 1 (152 จุด) ใช้ METHOD ของตำราตามตรง
-- ส่วนที่ 2 (23 จุด) อยู่เหนือช่องอกและซี่โครง คงมุมเฉียงไว้ตามที่ตกลงกัน
--   เอาเฉพาะความลึกมาจากตำรา ด้วยเหตุผลเดียวกับเส้น BL ST GB
-- CV-8 กับ CV-9 ไม่แตะ เพราะตำราห้ามใช้เข็ม และเว็บเขียนถูกอยู่แล้ว
-- ======================================================================

-- ---------- ส่วนที่ 1 ----------
update points p set
  needle_th = v.nth, needle_en = v.nen, verified = true,
  verified_source = coalesce(nullif(p.verified_source, ''),
                             'Xie''s Veterinary Acupuncture (2007) ch.5')
from (values
  ('CV-1', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('CV-2', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('CV-3', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-4', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-5', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-6', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-7', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-10', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-11', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-12', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-13', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3 cun'),
  ('CV-14', 'แทงขนานผิวหนัง ลึกราว 0.3 cun', 'Horizontal insertion: dry-needle depth 0.3 cun'),
  ('CV-22', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('CV-23', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.3-0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.3–0.5 cun'),
  ('CV-24', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5-1 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5–1 cun'),
  ('HT-1', 'แทงเฉียงขึ้น ลึกราว 0.5 cun', 'Oblique upward insertion: dry-needle depth 0.5 cun'),
  ('HT-2', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('HT-3', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('HT-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('HT-5', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('HT-6', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('HT-7', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('HT-8', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('HT-9', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('KID-1', 'แทงเฉียง ลึกราว 0.5-1 cun', 'Oblique insertion: dry-needle depth 0.5–1 cun'),
  ('KID-2', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-3', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-5', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-6', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-7', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-8', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-9', 'แทงตั้งฉากหรือเฉียง ลึกราว 1 cun', 'Perpendicular or oblique insertion: dry-needle depth 1 cun'),
  ('KID-10', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('KID-11', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3cun'),
  ('KID-12', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-13', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-14', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('KID-15', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-16', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-17', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-18', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-19', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-20', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('KID-21', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('LI-1', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('LI-2', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('LI-3', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LI-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LI-5', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LI-6', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LI-7', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LI-8', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LI-9', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LI-10', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('LI-11', 'แทงตั้งฉากหรือเฉียง ลึกราว 1.5 cun ทำ aquapuncture ได้', 'Perpendicular or oblique insertion: dry-needle depth 1.5 cun, aquapuncture depth 1 cun'),
  ('LI-12', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('LI-13', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('LI-14', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('LI-15', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('LI-16', 'แทงตั้งฉาก ลึกราว 1.5-2 cun', 'Perpendicular insertion: dry-needle depth 1.5–2 cun'),
  ('LI-17', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('LI-18', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('LI-19', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LI-20', 'แทงเฉียง ลึกราว 0.3 cun', 'Oblique insertion: dry-needle depth 0.3 cun'),
  ('LIV-1', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('LIV-2', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LIV-3', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LIV-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LIV-5', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LIV-6', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LIV-7', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LIV-8', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LIV-9', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LIV-10', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('LIV-11', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('LIV-12', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('LU-3', 'แทงตั้งฉาก ลึกราว 1 cun ทำ aquapuncture ได้', 'Perpendicular insertion: dry-needle depth 1 cun, aquapuncture depth 0.5 cun'),
  ('LU-4', 'แทงตั้งฉาก ลึกราว 1 cun ทำ aquapuncture ได้', 'Perpendicular insertion: dry-needle depth 1 cun, aquapuncture depth 0.5 cun'),
  ('LU-5', 'แทงตั้งฉาก ลึกราว 1.5 cun ทำ aquapuncture ได้', 'Perpendicular insertion: dry-needle depth 1.5 cun, aquapuncture depth 1 cun'),
  ('LU-6', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('LU-7', 'แทงเฉียงหรือตั้งฉาก ลึกราว 0.5 cun', 'Oblique or perpendicular insertion: dry-needle depth 0.5 cun'),
  ('LU-8', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('LU-9', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('LU-10', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('LU-11', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('PC-1', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion toward the elbow: dry-needle depth 0.5 cun'),
  ('PC-2', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('PC-3', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('PC-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('PC-5', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('PC-6', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('PC-7', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('PC-8', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('PC-9', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('SI-1', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('SI-2', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('SI-3', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('SI-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SI-5', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SI-6', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('SI-7', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SI-8', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SI-9', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SI-10', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SI-11', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SI-12', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('SI-13', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SI-14', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('SI-16', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SI-17', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SI-18', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('SI-19', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('SP-1', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('SP-2', 'แทงเฉียง ลึกราว 0.2-0.5 cun', 'Oblique insertion: dry-needle depth 0.2–0.5 cun'),
  ('SP-3', 'แทงเฉียง ลึกราว 0.2-0.5 cun', 'Oblique insertion: dry-needle depth 0.2–0.5 cun'),
  ('SP-4', 'แทงเฉียง ลึกราว 0.2-0.5 cun', 'Oblique insertion: dry-needle depth 0.2–0.5 cun'),
  ('SP-5', 'แทงเฉียงหรือตั้งฉาก ลึกราว 0.5 cun', 'Oblique or perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SP-6', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('SP-7', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('SP-8', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SP-9', 'แทงตั้งฉากหรือเฉียง ลึกราว 1 cun', 'Perpendicular or oblique insertion: dry-needle depth 1 cun'),
  ('SP-10', 'แทงตั้งฉากหรือเฉียง ลึกราว 1 cun', 'Perpendicular or oblique insertion: dry-needle depth 1 cun'),
  ('SP-11', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('SP-12', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SP-13', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('SP-14', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SP-15', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('SP-16', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-1', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2'),
  ('TH-2', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('TH-3', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-5', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-6', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-7', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-8', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-9', 'แทงเฉียง ลึกราว 1-3 cun', 'Oblique insertion toward PC-6: dry-needle depth 1–3 cun'),
  ('TH-10', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-11', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-12', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-13', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-14', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-15', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('TH-16', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('TH-17', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('TH-18', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('TH-19', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-20', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-21', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('TH-22', 'แทงเฉียง ลึกราว 1 cun', 'Oblique insertion: dry-needle depth 1 cun'),
  ('TH-23', 'แทงเฉียง ลึกราว 1 cun', 'Oblique insertion: dry-needle depth 1 cun')
) as v(code, nth, nen)
where p.code = v.code;

-- ---------- ส่วนที่ 2 ----------
update points p set
  needle_th = v.nth, needle_en = v.nen, verified = true,
  verified_source = 'Xie''s Veterinary Acupuncture (2007) ch.5 — ความลึกตามตำรา มุมเฉียงตามการใช้จริงในสัตว์เล็ก'
from (values
  ('CV-15', 'แทงเฉียงลงตามแนวกระดูกอก ลึกราว 0.3 cun', 'Oblique insertion caudally along the sternum, 0.3 cun (the text gives perpendicular at this depth)'),
  ('CV-16', 'แทงเฉียงขนานกระดูกอก ลึกราว 0.3-0.5 cun', 'Oblique insertion parallel to the sternum, 0.3-0.5 cun (the text gives perpendicular at this depth)'),
  ('CV-17', 'แทงเฉียงขนานกระดูกอก ลึกราว 0.5 cun', 'Oblique insertion parallel to the sternum, 0.5 cun (the text gives perpendicular at this depth)'),
  ('CV-18', 'แทงเฉียงขนานกระดูกอก ลึกราว 0.3-0.5 cun', 'Oblique insertion parallel to the sternum, 0.3-0.5 cun (the text gives perpendicular at this depth)'),
  ('CV-19', 'แทงเฉียงขนานกระดูกอก ลึกราว 0.3-0.5 cun', 'Oblique insertion parallel to the sternum, 0.3-0.5 cun (the text gives perpendicular at this depth)'),
  ('CV-20', 'แทงเฉียงขนานกระดูกอก ลึกราว 0.3-0.5 cun', 'Oblique insertion parallel to the sternum, 0.3-0.5 cun (the text gives perpendicular at this depth)'),
  ('CV-21', 'แทงเฉียงขนานกระดูกอก ลึกราว 0.5 cun', 'Oblique insertion parallel to the sternum, 0.5 cun (the text gives perpendicular at this depth)'),
  ('KID-22', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.3 cun', 'Oblique insertion along the rib, 0.3 cun (the text gives perpendicular at this depth)'),
  ('KID-23', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.2 cun', 'Oblique insertion along the rib, 0.2 cun (the text gives perpendicular at this depth)'),
  ('KID-24', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.3 cun', 'Oblique insertion along the rib, 0.3 cun (the text gives perpendicular at this depth)'),
  ('KID-25', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.3 cun', 'Oblique insertion along the rib, 0.3 cun (the text gives perpendicular at this depth)'),
  ('KID-26', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.3 cun', 'Oblique insertion along the rib, 0.3 cun (the text gives perpendicular at this depth)'),
  ('KID-27', 'แทงเฉียงตามแนวซี่โครง ลึกราว 1 cun', 'Oblique insertion along the rib, 1 cun (the text gives perpendicular at this depth)'),
  ('LIV-13', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.5-1 cun', 'Oblique insertion along the rib, 0.5-1 cun (the text gives perpendicular at this depth)'),
  ('LIV-14', 'แทงเฉียงตามแนวซี่โครง ลึกราว 1 cun', 'Oblique insertion along the rib, 1 cun (the text gives perpendicular at this depth)'),
  ('LU-1', 'แทงเฉียงไปทางหน้าอก ลึกราว 2 cun', 'Oblique insertion toward the chest, 2 cun (the text gives perpendicular at this depth)'),
  ('LU-2', 'แทงเฉียงตามแนวซี่โครง ลึกราว 1 cun', 'Oblique insertion along the rib, 1 cun (the text gives perpendicular at this depth)'),
  ('SI-15', 'แทงเฉียงเข้าหาแนวกลาง ลึกราว 1 cun', 'Oblique insertion toward the midline, 1 cun (the text gives perpendicular at this depth)'),
  ('SP-17', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.5 cun', 'Oblique insertion along the rib, 0.5 cun (the text gives perpendicular at this depth)'),
  ('SP-18', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.5 cun', 'Oblique insertion along the rib, 0.5 cun (the text gives perpendicular at this depth)'),
  ('SP-19', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.5 cun', 'Oblique insertion along the rib, 0.5 cun (the text gives perpendicular at this depth)'),
  ('SP-20', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.5 cun', 'Oblique insertion along the rib, 0.5 cun (the text gives perpendicular at this depth)'),
  ('SP-21', 'แทงเฉียงตามแนวซี่โครง ลึกราว 0.5 cun', 'Oblique insertion along the rib, 0.5 cun (the text gives perpendicular at this depth)')
) as v(code, nth, nen)
where p.code = v.code;

-- ---------- ข้อควรระวังที่ตำราระบุไว้เอง ----------
-- ตำรามีหัวข้อ CAUTIONS ที่ KI-11, KI-12 และ KI-13 ว่าแทงลึกอาจทะลุ
-- กระเพาะปัสสาวะที่เต็ม ของเรามีเฉพาะที่ KI-11 จึงเติมอีกสองจุด
update points set
  caution_th = trim(both ' ' from coalesce(caution_th || ' · ', '') || 'ให้สัตว์ปัสสาวะก่อน แทงลึกอาจทะลุกระเพาะปัสสาวะที่เต็ม'),
  caution_en = trim(both ' ' from coalesce(caution_en || ' - ', '') || 'Have the animal urinate first; deep needling may penetrate a full urinary bladder')
where code in ('KID-12','KID-13')
  and (caution_th is null or caution_th not like '%กระเพาะปัสสาวะ%');

-- ---------- ตรวจผล: ควรไม่เหลือจุดไหนเป็น ซม. อีกเลยทั้งเว็บ ----------
select meridian_code,
       count(*) filter (where needle_th like '%cun%') as cun,
       count(*) filter (where needle_th like '%ซม.%') as ซม,
       count(*)                                         as ทั้งหมด
from points group by meridian_code order by ซม desc, meridian_code;

select code, needle_th from points where needle_th like '%ซม.%' order by code;
