-- =============================================================
-- JFK — คำแปลอังกฤษของจุดหลัก 100 จุด (verified)
-- รันหลัง supabase-migration-i18n.sql
-- =============================================================

update points set
  location_en    = v.loc,
  anatomy_en     = v.ana,
  functions_en   = v.fun,
  indications_en = v.ind,
  needle_en      = v.ndl,
  caution_en     = v.cau
from (values

-- ===== LU =====
('LU-1','In the first intercostal space on the lateral chest, cranio-ventral to the shoulder joint; palpate for the soft depression above the border of the sternum.','1st-2nd intercostal space, over the cranial pectoral muscle.','Disperses lung qi and relieves chest oppression.','{cough,dyspnoea,bronchitis,shoulder pain,chest oppression}','Oblique toward the chest wall, 0.3-0.5 cm, 0.20 x 25 mm needle.','Never perpendicular or deep — risk of pneumothorax.'),
('LU-5','On the cranial aspect of the elbow, in the depression lateral to the tendon of biceps brachii; the depression is clearest with the elbow flexed.','Cranial elbow crease, beside the biceps brachii tendon.','Clears heat from the lung, stops cough, relaxes the elbow.','{cough,dyspnoea,bronchitis,elbow pain,fever}','Perpendicular 0.5-1 cm.',null),
('LU-7','On the cranio-medial distal forelimb, about 1.5 cun proximal to the carpus, above the styloid process of the radius.','Medial border of the distal radius, proximal to the carpus.','Releases the exterior, opens the nose, relaxes the neck.','{cough,common cold,nasal congestion,neck pain,carpal pain}','Oblique proximally, 0.3-0.5 cm.',null),
('LU-9','At the cranio-medial carpal crease, just medial to the radial artery, where the pulse is palpable.','Cranio-medial carpal crease beside the radial artery.','Tonifies lung qi; influential point of the vessels.','{chronic cough,dyspnoea,lung deficiency,carpal pain}','Perpendicular 0.3 cm, avoiding the vessel.',null),
('LU-11','At the nail bed of the second digit of the forelimb, on its medial side.','Ting point at the medial nail bed of digit 2.','Opens the orifices, restores consciousness, clears acute heat.','{emergency,high fever,shock,sore throat,collapse}','Very shallow, 1-2 mm, or bleed 1-2 drops with a 25G needle.','Painful — leave until last in the session.'),

-- ===== LI =====
('LI-1','At the nail bed of the second digit of the forelimb, on its lateral side.','Ting point at the lateral nail bed of digit 2.','Clears heat and restores consciousness.','{emergency,fever,shock,sore throat}','Shallow 1-2 mm, or bleed.','Painful — leave until last.'),
('LI-4','On the dorsal forepaw, in the groove between the second and third metacarpal bones, at mid-shaft.','Groove between metacarpals II and III, dorsal surface.','Relieves pain throughout the body, releases wind and heat; command point of the face and mouth.','{analgesia,fever,dental pain,allergy,nasal congestion,constipation,facial paralysis}','Perpendicular 0.5-1 cm.','Contraindicated in pregnancy — stimulates uterine contraction.'),
('LI-10','On the lateral forelimb about 2 cun distal to the elbow, in the groove of extensor carpi radialis.','Extensor carpi radialis on the lateral antebrachium.','Regulates the intestines and relaxes the forelimb muscles.','{forelimb pain,forelimb paresis,diarrhoea,muscle weakness}','Perpendicular 0.5-1.5 cm.',null),
('LI-11','On the lateral elbow, in the depression between the lateral epicondyle of the humerus and the head of the radius.','Depression on the lateral elbow, above the radial head.','Clears heat and toxin from the blood, stops itching, frees the elbow.','{pruritus,allergy,fever,elbow pain,diarrhoea,rash}','Perpendicular 0.5-1.5 cm.',null),
('LI-16','Cranial to the scapular spine, cranio-dorsal to the shoulder joint, in the depression between the cranial scapular border and the shoulder muscles.','Cranial border of the scapula above the shoulder joint.','Frees the shoulder and relieves neck and shoulder pain.','{shoulder pain,forelimb lameness,neck pain}','Oblique ventrally, 0.5-1 cm.',null),
('LI-20','Beside the nostril, in the nasolabial groove at the level of the nose.','Nasolabial groove beside the nostril.','Opens the nose and releases wind from the face.','{nasal congestion,sneezing,epistaxis,rhinitis,facial paralysis}','Oblique toward the nose, shallow 0.2-0.4 cm.','A sensitive point — steady the head well.'),

-- ===== ST =====
('ST-2','Below the orbit at the infraorbital foramen; palpate the depression below the ventral border of the zygomatic bone.','Infraorbital foramen and infraorbital nerve.','Releases wind from the face and benefits the eyes.','{conjunctivitis,facial paralysis,facial pain,epiphora}','Shallow 0.2-0.5 cm.','Do not enter the foramen deeply — risk of nerve trauma.'),
('ST-6','At the angle of the mandible, over masseter, at the point that bulges most when the animal clenches.','Masseter muscle above the mandibular angle.','Relaxes the muscles of mastication and releases wind from the face.','{jaw pain,trismus,facial paralysis,dental pain,masticatory myositis}','Perpendicular 0.5-1 cm.',null),
('ST-7','Cranial to the temporomandibular joint, in the depression below the ventral border of the zygomatic arch.','Depression cranial to the TMJ, below the zygomatic arch.','Frees the jaw joint and relieves ear pain.','{TMJ pain,jaw pain,otitis,trismus}','Perpendicular 0.5-1 cm.',null),
('ST-25','Lateral to the umbilicus, about 2 cun from the ventral midline, bilaterally.','Abdominal wall lateral to rectus abdominis at the level of the umbilicus.','Regulates intestinal motility in both diarrhoea and constipation.','{diarrhoea,constipation,enteritis,abdominal pain,bloating}','Perpendicular and shallow, 0.5-1 cm; tent the skin in a thin animal.','Care in marked bloat or an abdominal mass.'),
('ST-35','In the depression lateral to the patellar ligament; clearest with the stifle flexed.','Depression lateral to the patellar ligament at the stifle.','Frees the stifle, reduces swelling and pain.','{stifle pain,osteoarthritis of the stifle,cruciate disease,patellar luxation,joint effusion}','Oblique into the joint space, 0.5-1 cm.','Strict aseptic technique — close to the joint.'),
('ST-36','On the lateral aspect of the crus, in the groove between the tibia and the cranial tibial muscle, about 3 cun distal to ST-35.','Groove along the cranial border of the tibia over cranial tibial muscle.','The strongest qi and blood tonic; regulates stomach and intestines and supports immunity.','{inappetence,vomiting,diarrhoea,weakness,poor immunity,hindlimb weakness,geriatric,post-operative}','Perpendicular 1-2 cm; 0.25 x 40 mm in a large dog.','No significant contraindications — the safest and most used point.'),
('ST-40','On the lateral crus, midway between stifle and hock, in the muscular groove lateral to the tibia.','Peroneus / digital extensor on the lateral crus.','Resolves phlegm and directs qi downward.','{productive cough,dyspnoea,obesity,seizures,nausea}','Perpendicular 1-1.5 cm.',null),
('ST-41','At the middle of the cranial aspect of the hock crease, between the two palpable extensor tendons.','Mid cranial tarsus between the extensor tendons.','Frees the hock and clears stomach heat.','{hock pain,hindlimb paresis,limb oedema,knuckling}','Perpendicular, shallow 0.3-0.5 cm.',null),
('ST-44','On the dorsal hindpaw, in the groove between the third and fourth digits near the distal metatarsus.','Interdigital groove 3-4, dorsal hindpaw.','Clears stomach heat.','{fever,dental pain,stomach heat,bloating,halitosis}','Oblique, shallow 0.3 cm.',null),
('ST-45','At the nail bed of the third digit of the hindlimb, on its lateral side.','Ting point at the nail bed of hind digit 3.','Clears heat and restores consciousness.','{emergency,fever,restlessness,shock}','Shallow 1-2 mm, or bleed.','Painful — leave until last.'),

-- ===== SP =====
('SP-3','On the medial hindpaw at the base of the second metatarsal bone, in the depression between bone and skin.','Medial aspect of the base of metatarsal II.','Tonifies the spleen and transforms damp.','{spleen deficiency,chronic diarrhoea,inappetence,weakness,bloating}','Perpendicular, shallow 0.3-0.5 cm.',null),
('SP-6','On the medial crus about 3 cun proximal to the tip of the medial malleolus, against the caudal border of the tibia.','Caudo-medial border of the tibia; meeting point of the spleen, liver and kidney channels.','Nourishes blood and yin, regulates the urogenital tract, calms the spirit.','{blood tonification,insomnia,dysuria,bloating,irregular cycles,dry skin,renal disease}','Perpendicular 0.5-1.5 cm.','Contraindicated in pregnancy.'),
('SP-9','On the medial hindlimb in the depression below the medial condyle of the tibia.','Depression below the medial tibial condyle.','Drains damp and regulates urination.','{oedema,diarrhoea,dysuria,stifle effusion,ascites}','Perpendicular 0.5-1.5 cm.',null),
('SP-10','On the medial thigh about 2 cun proximal to the patella, over vastus medialis.','Vastus medialis above the medial stifle.','Cools the blood, stops itching and nourishes blood.','{pruritus,atopic dermatitis,rash,anaemia,metritis}','Perpendicular 0.5-1.5 cm.',null),
('SP-21','On the lateral trunk in the 11th intercostal space, at mid-body height.','11th intercostal space at mid-trunk.','Frees the channels of the whole body and harmonises blood and qi.','{generalised pain,muscle weakness,flank pain,fibromyalgia}','Oblique along the rib, 0.3-0.5 cm.','Never perpendicular and deep — risk of pneumothorax.'),

-- ===== HT =====
('HT-3','On the medial elbow, in the depression between the medial epicondyle of the humerus and the flexor tendon.','Medial elbow depression near the ulnar nerve.','Drains heart fire, calms the spirit, frees the elbow.','{elbow pain,restlessness,seizures,palpitations}','Perpendicular 0.5-1 cm.','Watch the ulnar nerve — withdraw slightly if the animal twitches.'),
('HT-7','On the medial carpal crease, in the depression just medial to the accessory carpal bone.','Medial carpal crease beside the accessory carpal bone.','Calms the spirit and tonifies the heart — the principal point for behaviour work.','{anxiety,insomnia,panic,seizures,palpitations,aggression,noise phobia}','Perpendicular, shallow 0.3-0.5 cm.','Animals dislike having the carpus held — stroke the limb first.'),
('HT-9','At the nail bed of the fifth (outermost) digit of the forelimb, on its medial side.','Ting point at the medial nail bed of digit 5.','Opens the orifices, restores consciousness, drains heart fire.','{emergency,shock,collapse,palpitations,seizures}','Shallow 1-2 mm, or bleed.','Painful — leave until last.'),

-- ===== SI =====
('SI-1','At the nail bed of the fifth digit of the forelimb, on its lateral side.','Ting point at the lateral nail bed of digit 5.','Clears heat and promotes lactation.','{emergency,fever,agalactia,mastitis}','Shallow 1-2 mm, or bleed.',null),
('SI-3','On the lateral border of the forepaw, in the depression near the base of the fifth metacarpal bone.','Lateral palm near the base of metacarpal V.','Opens the Governing Vessel, frees the neck and back, stops seizures.','{neck pain,torticollis,back pain,seizures,cervical disc disease,fever}','Perpendicular 0.3-0.7 cm.',null),
('SI-9','Caudo-ventral to the shoulder joint, in the depression caudal to the head of the humerus at the level of the joint.','Depression caudal to the shoulder between deltoideus and triceps.','Frees the shoulder and regulates the forelimb channels.','{shoulder pain,forelimb paresis,forelimb lameness,brachial plexus injury}','Perpendicular 1-2 cm.',null),
('SI-19','Cranial to the base of the ear, in the depression cranio-ventral to the ear base at the level of the ear canal.','Depression cranial to the ear base near the external ear canal.','Opens the ear orifice and clears heat from the ear.','{otitis,deafness,vestibular signs,head tilt,itchy ears}','Oblique ventrally, 0.3-0.5 cm.','Do not needle into the ear canal.'),

-- ===== BL =====
('BL-10','On the lateral neck, in the depression lateral to the caudal border of the wing of the atlas, about 1.5 cun from the dorsal midline.','Depression beside the wing of the atlas over the cervical muscles.','Frees the neck and releases wind from the head.','{neck pain,cervical stiffness,seizures,head tilt,blurred vision}','Perpendicular 0.5-1 cm.','Never deep enough to reach the vertebral canal.'),
('BL-11','1.5 cun lateral to the dorsal midline at the 1st intercostal space (T1-T2 level).','1st intercostal space beside the epaxial muscles.','Influential point of bone; frees the neck and shoulder.','{neck pain,shoulder pain,osteopenia,osteoarthritis,cough}','Oblique 45 degrees toward the midline, 0.5-1 cm.','Never perpendicular and deep — pneumothorax risk.'),
('BL-13','1.5 cun lateral to the dorsal midline at the 3rd intercostal space.','3rd intercostal space over the epaxial muscles.','Regulates lung qi — the back-shu point of the lung.','{cough,dyspnoea,bronchitis,feline asthma,allergy,common cold}','Oblique 30-45 degrees toward the midline, 0.5-1 cm.','Never perpendicular — pneumothorax risk.'),
('BL-14','1.5 cun lateral to the dorsal midline at the 4th intercostal space.','4th intercostal space.','Regulates the pericardium and relieves chest oppression.','{palpitations,chest oppression,cough,nausea}','Oblique toward the midline, 0.5-1 cm.','Never perpendicular.'),
('BL-15','1.5 cun lateral to the dorsal midline at the 5th intercostal space.','5th intercostal space.','Tonifies the heart and calms the spirit.','{palpitations,anxiety,insomnia,seizures,cardiomegaly}','Oblique toward the midline, 0.5-1 cm.','Never perpendicular.'),
('BL-17','1.5 cun lateral to the dorsal midline at the 7th intercostal space.','7th intercostal space at the level of the diaphragm.','Tonifies and regulates blood — the key blood point of the body.','{anaemia,vomiting,hiccups,pruritus,abnormal bleeding,blood tonification}','Oblique toward the midline, 0.5-1 cm.','Never perpendicular.'),
('BL-18','1.5 cun lateral to the dorsal midline at the 10th intercostal space.','10th intercostal space.','Regulates the liver and benefits the eyes and sinews.','{hepatitis,red eyes,seizures,tight sinews,irritability,jaundice}','Oblique toward the midline, 0.5-1 cm.',null),
('BL-19','1.5 cun lateral to the dorsal midline at the 11th intercostal space.','11th intercostal space.','Clears damp-heat from the liver and gall bladder.','{jaundice,hepatitis,bilious vomiting,inappetence}','Oblique toward the midline, 0.5-1 cm.',null),
('BL-20','1.5 cun lateral to the dorsal midline at the 12th intercostal space.','12th intercostal space.','Tonifies the spleen and supports digestion.','{inappetence,chronic diarrhoea,weakness,weight loss,bloating,spleen deficiency}','Oblique toward the midline, 0.5-1 cm.',null),
('BL-21','1.5 cun lateral to the dorsal midline, just caudal to the last rib (13th space).','Caudal to the last rib over the epaxial muscles.','Regulates the stomach and reduces vomiting.','{vomiting,inappetence,gastritis,bloating,reflux}','Oblique toward the midline, 0.5-1.5 cm.',null),
('BL-22','1.5 cun lateral to the dorsal midline at the level of the first lumbar vertebra.','L1 level over the epaxial muscles.','Regulates water metabolism.','{oedema,oliguria,bloating,back pain}','Perpendicular-oblique toward the midline, 1-2 cm.',null),
('BL-23','1.5 cun lateral to the dorsal midline between the second and third lumbar vertebrae.','L2-L3 level over the epaxial muscles above the kidney.','Tonifies the kidney and strengthens the bones and lower back — the principal point of the geriatric patient.','{renal disease,back pain,hindlimb paresis,geriatric,hindlimb weakness,deafness,pollakiuria,hip dysplasia}','Perpendicular-oblique toward the midline, 1-2.5 cm by size.','Do not needle straight down deeply into the abdomen.'),
('BL-25','1.5 cun lateral to the dorsal midline at the fifth lumbar vertebra.','L5 level over the epaxial muscles.','Regulates the large intestine and frees the lower back.','{constipation,diarrhoea,lumbar pain,hindlimb paresis,intervertebral disc disease}','Perpendicular 1-2.5 cm.',null),
('BL-26','1.5 cun lateral to the dorsal midline at the sixth lumbar vertebra.','L6 level.','Tonifies lower yang and regulates the back and hindlimbs.','{lumbar pain,hindlimb weakness,urinary incontinence,lumbosacral pain}','Perpendicular 1-2.5 cm.',null),
('BL-27','1.5 cun lateral to the dorsal midline at the lumbosacral junction (L7-S1).','L7-S1 level.','Regulates the small intestine and frees the lumbosacral region.','{diarrhoea,lumbosacral pain,weak tail,urinary disorders}','Perpendicular 1-2 cm.',null),
('BL-28','1.5 cun lateral to the dorsal midline at the second sacral foramen.','S2 level on the sacrum.','Regulates the bladder.','{cystitis,dysuria,urinary incontinence,FLUTD,loss of bladder control}','Perpendicular-oblique 0.5-1.5 cm.',null),
('BL-40','In the middle of the popliteal crease, between the tendons of biceps femoris and semitendinosus.','Centre of the popliteal fossa.','Frees the lower back and cools the blood; command point of the back.','{back pain,hindlimb paresis,stifle pain,dermatitis,cramp}','Perpendicular 0.5-1.5 cm.','Avoid the vessels and nerve in the centre of the fossa.'),
('BL-54','Lateral to the caudal sacrum, about 3 cun from the dorsal midline, in the depression cranio-dorsal to the greater trochanter.','Depression lateral to the sacrum above the hip joint.','Frees the hip and lower back.','{hindlimb paresis,hip dysplasia,lumbosacral pain,intervertebral disc disease}','Perpendicular 1.5-3 cm by size.',null),
('BL-60','In the depression between the lateral malleolus and the calcaneal tendon.','Depression between the lateral malleolus and the calcaneal tendon.','Frees the back and neck and stops seizures.','{back pain,neck pain,hock pain,seizures,dystocia}','Perpendicular 0.3-0.7 cm.','Contraindicated in pregnancy.'),
('BL-62','Below the lateral malleolus, in the depression above the calcaneus.','Depression below the lateral malleolus.','Opens the Yang Qiao vessel and stops seizures.','{seizures,back pain,insomnia,hock sprain}','Perpendicular, shallow 0.3-0.5 cm.',null),
('BL-67','At the nail bed of the fifth digit of the hindlimb, on its lateral side.','Ting point at the nail bed of hind digit 5.','Corrects fetal position and releases wind from the head.','{fetal malposition,headache,emergency,red eyes}','Shallow 1-2 mm, or moxa.','Use moxa for fetal malposition only; otherwise avoid in pregnancy.')

) as v(code, loc, ana, fun, ind, ndl, cau)
where points.code = v.code;

update points set
  location_en    = v.loc,
  anatomy_en     = v.ana,
  functions_en   = v.fun,
  indications_en = v.ind,
  needle_en      = v.ndl,
  caution_en     = v.cau
from (values

-- ===== KI =====
('KI-1','On the plantar surface of the hindpaw, in the groove between the third and fourth metatarsal bones, at the centre of the pad region.','Plantar hindpaw, groove between metatarsals III and IV.','Draws fire downward and restores consciousness immediately.','{emergency,shock,collapse,heat stroke,seizures}','Shallow 0.2-0.5 cm, or strong stimulation with the needle tip.','Very painful — reserve for emergencies.'),
('KI-3','On the medial aspect of the hock, in the depression between the medial malleolus and the calcaneal tendon (opposite BL-60).','Depression between the medial malleolus and the calcaneal tendon.','Tonifies both kidney yin and yang — the principal geriatric point.','{renal disease,back pain,deafness,geriatric,hindlimb weakness,pollakiuria,emaciation}','Perpendicular 0.3-0.7 cm.',null),
('KI-6','Below the medial malleolus, in the small depression on the medial hock.','Depression below the medial malleolus.','Nourishes yin and regulates body fluids.','{dry throat,insomnia,dysuria,yin deficiency,constipation}','Perpendicular, shallow 0.3-0.5 cm.',null),
('KI-7','On the medial crus about 2 cun proximal to KI-3, against the caudal border of the tibia.','Caudo-medial border of the tibia above the hock.','Moves water, regulates sweating, tonifies the kidney.','{oedema,oliguria,abnormal sweating,diarrhoea}','Perpendicular 0.5-1 cm.',null),
('KI-10','At the medial end of the popliteal crease, between the tendons of semitendinosus and gracilis.','Medial end of the popliteal fossa.','Clears damp-heat from the urinary tract.','{dysuria,cystitis,medial stifle pain}','Perpendicular 0.5-1 cm.',null),

-- ===== PC =====
('PC-6','On the medial forelimb about 2 cun proximal to the carpal crease, in the groove between the digital flexor tendons.','Between flexor carpi radialis and superficial digital flexor.','Regulates qi in the chest, stops nausea and vomiting, calms the spirit.','{vomiting,nausea,motion sickness,palpitations,chest oppression,anxiety,hiccups,chemotherapy nausea}','Perpendicular 0.5-1 cm.',null),
('PC-7','At the middle of the medial carpal crease, between the digital flexor tendons.','Middle of the medial carpal crease.','Calms the spirit and drains pericardium fire.','{anxiety,palpitations,insomnia,carpal pain,seizures}','Perpendicular, shallow 0.3-0.5 cm.',null),
('PC-9','At the tip of the third digit of the forelimb, at the cranial nail bed.','Ting point at the tip of digit 3.','Restores consciousness and clears acute heat.','{emergency,shock,heat stroke,collapse,high fever}','Shallow 1-2 mm, or bleed.','Painful — leave until last.'),

-- ===== TH =====
('TH-1','At the nail bed of the fourth digit of the forelimb, on its lateral side.','Ting point at the lateral nail bed of digit 4.','Clears heat and opens the ear orifice.','{fever,otitis,emergency,sore throat}','Shallow 1-2 mm, or bleed.',null),
('TH-5','On the lateral forelimb about 2 cun proximal to the carpal crease, in the groove between radius and ulna (opposite PC-6).','Groove between radius and ulna, lateral aspect above the carpus.','Releases the exterior, opens the ear, relieves pain along the lateral forelimb.','{common cold,fever,otitis,forelimb pain,allergy,neck stiffness}','Perpendicular 0.5-1 cm.',null),
('TH-14','In the depression on the lateral shoulder, caudal to the acromion.','Depression caudal to the acromion over deltoideus.','Frees the shoulder joint.','{shoulder pain,forelimb lameness,frozen shoulder}','Perpendicular 1-2 cm.',null),
('TH-17','In the depression behind the base of the ear, between the ear base and the cranial border of the wing of the atlas.','Depression behind the ear base near the facial nerve.','Releases wind from the face and opens the ear orifice.','{otitis,facial paralysis,vestibular signs,head tilt,jaw pain}','Oblique toward the ear base, 0.5-1 cm.','Do not needle deeply toward the skull base.'),

-- ===== GB =====
('GB-20','In the occipital depression lateral to the caudal border of the nuchal crest, bilaterally.','Depression between the cervical muscles and the nuchal crest.','Releases wind from the head, frees the neck, benefits the eyes.','{neck pain,cervical stiffness,seizures,vertigo,common cold,red eyes,cervical disc disease}','Oblique toward the midline, 0.5-1.5 cm.','Never directed into the skull base or vertebral canal.'),
('GB-21','Midway between the cranial border of the scapula and the dorsal midline, over trapezius.','Trapezius cranial to the scapula.','Directs qi downward and frees the shoulder and neck.','{shoulder pain,neck pain,mastitis,dystocia,muscle spasm}','Oblique 0.5-1.5 cm.','Contraindicated in pregnancy.'),
('GB-29','In the depression cranial to the greater trochanter of the femur.','Depression cranial to the greater trochanter.','Frees the hip joint.','{hip dysplasia,hip pain,hindlimb lameness}','Perpendicular 1-2.5 cm.',null),
('GB-30','In the depression caudal to the greater trochanter, midway between the trochanter and the ischiatic tuberosity.','Depression caudal to the greater trochanter over the sciatic nerve.','Frees the hip and hindlimb and relieves sciatic pain.','{hindlimb paresis,hip dysplasia,hindlimb pain,sciatic pain,lameness}','Perpendicular 1.5-4 cm by size; a twitch may be felt at nerve depth.','Withdraw slightly if the animal twitches strongly.'),
('GB-34','On the lateral hindlimb in the depression cranio-distal to the head of the fibula, below the stifle.','Depression cranial to the fibular head.','Relaxes sinews and muscle throughout the body; regulates liver and gall bladder.','{tight sinews,stifle pain,cramp,muscle spasm,osteoarthritis,jaundice,hindlimb paresis}','Perpendicular 0.5-2 cm.',null),
('GB-39','On the lateral crus about 3 cun proximal to the lateral malleolus, against the cranial border of the fibula.','Cranial border of the fibula above the hock.','Influential point of marrow; frees the neck.','{neck stiffness,paresis,bone and spinal cord disease,hock pain}','Perpendicular 0.5-1 cm.',null),
('GB-44','At the nail bed of the fourth digit of the hindlimb, on its lateral side.','Ting point at the nail bed of hind digit 4.','Drains liver and gall bladder fire.','{fever,red eyes,emergency,otitis}','Shallow 1-2 mm, or bleed.',null),

-- ===== LIV =====
('LIV-2','On the dorsal hindpaw, in the groove between the second and third digits near the distal metatarsus.','Interdigital groove 2-3, dorsal hindpaw.','Drains liver fire.','{red eyes,seizures,aggression,irritability,fever,hypertension}','Oblique, shallow 0.3 cm.',null),
('LIV-3','On the dorsal hindpaw, in the groove between the second and third metatarsal bones at mid-shaft.','Groove between metatarsals II and III, dorsal surface.','Regulates liver qi, relieves stress, stops seizures; with LI-4 forms the Four Gates.','{seizures,stress,aggression,red eyes,liver disease,chronic pain,tight sinews}','Perpendicular 0.3-0.7 cm.',null),
('LIV-8','At the medial end of the popliteal crease, cranial to the medial tendon.','Medial end of the popliteal crease.','Nourishes liver blood and clears damp-heat from the lower body.','{medial stifle pain,dysuria,anaemia,metritis}','Perpendicular 0.5-1.5 cm.',null),
('LIV-13','At the free end of the last floating rib, on the lateral trunk.','Free end of the last floating rib.','Regulates the spleen and liver and relieves bloating; influential point of the zang organs.','{bloating,inappetence,spleen deficiency,liver disease,flank pain}','Oblique along the rib, 0.5-1 cm.','Never perpendicular and deep — risk of abdominal penetration.'),
('LIV-14','On the lateral trunk in the 6th intercostal space at the level of the costochondral junction.','6th intercostal space at the costochondral junction.','Moves stagnant liver qi.','{hepatitis,vomiting,flank pain,inappetence,jaundice}','Oblique along the rib, 0.3-0.5 cm.','Never perpendicular — pneumothorax risk.'),

-- ===== CV =====
('CV-3','On the ventral midline about 1 cun cranial to the cranial border of the pubis.','Ventral midline of the caudal abdomen over the bladder.','Regulates the bladder and clears damp-heat from the lower body.','{cystitis,dysuria,FLUTD,urinary incontinence,urolithiasis}','Oblique caudally 0.5-1 cm; let the animal urinate first.','Never needle over a full bladder — risk of puncture. Contraindicated in pregnancy.'),
('CV-4','On the ventral midline between the umbilicus and the pubis, about two fifths of the way from the pubis.','Ventral midline of the caudal abdomen.','Tonifies original yang and source qi.','{weakness,chronic diarrhoea,urinary incontinence,geriatric,chronic deficiency,emaciation}','Oblique, shallow 0.5-1 cm; better suited to moxa than deep needling.','Contraindicated in pregnancy.'),
('CV-6','On the ventral midline about 1.5 cun caudal to the umbilicus.','Ventral midline caudal to the umbilicus.','Tonifies the qi of the whole body.','{weakness,bloating,diarrhoea,deficiency states,post-operative}','Oblique, shallow 0.5-1 cm, or moxa.','Contraindicated in pregnancy.'),
('CV-12','On the ventral midline midway between the xiphoid process and the umbilicus.','Ventral midline cranial to the umbilicus, over the stomach.','Regulates the stomach and reduces vomiting and bloating.','{vomiting,inappetence,gastritis,bloating,reflux,megaoesophagus}','Oblique, shallow 0.5-1 cm.','Care in marked gastric distension.'),
('CV-17','On the midline of the sternum at the level of the 4th intercostal space.','Mid-sternum at the 4th intercostal space.','Regulates qi in the chest and promotes lactation; influential point of qi.','{cough,dyspnoea,chest oppression,agalactia,tracheal collapse,cardiac disease}','Oblique, shallow 0.3-0.5 cm, parallel to the sternum.','Never perpendicular and deep.'),
('CV-22','On the ventral midline of the neck, in the depression cranial to the manubrium.','Depression at the thoracic inlet, ventral to the trachea.','Directs qi downward and stops cough.','{cough,tracheal collapse,hoarseness,laryngeal paralysis,dyspnoea,choking}','Oblique caudally, parallel to the trachea, shallow 0.3-0.5 cm.','Never perpendicular — risk to the trachea and great vessels.'),

-- ===== GV =====
('GV-1','On the midline below the tail base, in the depression between the tail base and the anus.','Depression between the tail base and the anus.','Raises yang and regulates the anus and tail.','{rectal prolapse,constipation,diarrhoea,weak tail,emergency,faecal incontinence}','Oblique cranially, parallel to the coccygeal vertebrae, 0.5-1.5 cm.','Clean the area first — contamination risk.'),
('GV-3','On the dorsal midline in the interspinous space between the fifth and sixth lumbar vertebrae.','L5-L6 interspinous space.','Awakens yang in the lower back.','{lumbar pain,hindlimb paresis,intervertebral disc disease,hindlimb weakness}','Perpendicular 0.5-2 cm into the interspinous space.','Do not reach the vertebral canal.'),
('GV-4','On the dorsal midline between the second and third lumbar vertebrae, level with BL-23.','L2-L3 interspinous space.','Tonifies kidney yang — the warming point for the geriatric patient.','{renal disease,back pain,hindlimb weakness,geriatric,chronic diarrhoea,cold intolerance,yang deficiency}','Perpendicular 0.5-2 cm; especially suited to moxa.','Do not reach the vertebral canal.'),
('GV-14','On the dorsal midline between the last cervical and first thoracic vertebra (C7-T1); palpate the most prominent spinous process at the base of the neck.','C7-T1 interspinous space.','Clears heat from the whole body, supports immunity, raises yang.','{fever,common cold,poor immunity,neck pain,seizures,cervical disc disease,cancer supportive care}','Oblique caudally, 0.5-1.5 cm.','Do not needle straight down — risk to the spinal cord.'),
('GV-20','On the head, on the dorsal midline at the level midway between the ear bases.','Dorsal midline of the cranium over the sagittal crest.','Raises yang, calms the spirit, opens the mind.','{seizures,calming,rectal prolapse,vertigo,canine cognitive dysfunction,vestibular signs}','Oblique, shallow 0.2-0.5 cm, parallel to the skull.','Never perpendicular and deep. Note: the Bai-hui most used in veterinary practice is the classical lumbosacral point, not GV-20.'),
('GV-26','On the facial midline, in the philtrum below the nose at the ventral border of the nostrils.','Philtrum below the nose.','Restores consciousness immediately and stimulates respiration — the principal resuscitation point.','{shock,collapse,respiratory arrest,CPR,seizures,heat stroke,drowning,non-breathing neonate}','Oblique cranially toward the nose, 0.2-0.5 cm, then strong stimulation by rotating or lifting the needle; in an emergency finger pressure works.','Use alongside standard resuscitation, never instead of it.'),

-- ===== EX classical points =====
('BAI-HUI','On the dorsal midline in the lumbosacral space between the last lumbar vertebra (L7) and the sacrum (S1) — the softest depression on the caudal dorsal midline.','Lumbosacral space (L7-S1).','The principal point for the lower back and hindlimbs; raises yang and relieves pain — the most used point in veterinary acupuncture.','{hindlimb paresis,intervertebral disc disease,IVDD,back pain,hip dysplasia,hindlimb weakness,diarrhoea,urinary incontinence,geriatric,degenerative myelopathy}','Perpendicular 1-3 cm by size; well suited to electroacupuncture paired with GV-3 or BL-23.','Do not reach the spinal cord in a small patient.'),
('JIA-JI','A set of points on both sides of the dorsal midline, about 0.5-1 cun lateral, at every interspinous space from the neck to the sacrum.','Interspinous spaces at every level, lateral to the midline over the epaxial muscles.','Opens the channels along the spine; needled bracketing the affected level.','{intervertebral disc disease,IVDD,back pain,paresis,spondylosis,neck stiffness,wobbler syndrome}','Oblique 30-45 degrees toward the midline, 0.5-2 cm; choose two or three levels above and below the lesion, usually with electroacupuncture across it.','Over the thorax, never perpendicular and deep — pneumothorax risk.'),
('DA-FENG-MEN','On the dorsal midline of the head, at the highest point between the ear bases, over the occipital protuberance.','Dorsal midline of the cranium over the external occipital protuberance.','Releases exterior wind and calms the spirit.','{common cold,fever,seizures,agitation,head tilt}','Oblique, shallow 0.2-0.5 cm.','Never perpendicular and deep.'),
('SHAN-GEN','On the midline of the nasal bridge, at the junction between the haired skin and the hairless nasal planum.','Midline of the nasal bridge at the skin-planum junction.','Restores consciousness and clears acute heat.','{emergency,shock,collapse,high fever,heat stroke,seizures}','Bleed with a sharp 25G needle, 1-2 mm deep, until 2-3 drops appear.','Painful and the animal will jerk its head — restrain firmly.'),
('AN-SHEN','In the depression below the ear base, between the ear base and the cranial border of the wing of the atlas (below and behind TH-17).','Depression below the ear base.','Calms the spirit and settles panic.','{anxiety,panic,seizures,otitis,aggression,noise phobia}','Oblique 0.3-0.8 cm.','Do not needle deeply toward the skull base.'),
('ER-JIAN','At the tip of the ear, over the vessel at the ear margin.','Vessel at the tip of the pinna.','Cools the blood and clears heat and toxin.','{high fever,heat stroke,red eyes,dermatitis,hypertension}','Bleeding technique: swab with alcohol, milk the ear tip to engorge the vessel, prick with a 25G needle and let 3-5 drops out.','Avoid in bleeding disorders or thrombocytopenia.'),
('WEI-JIAN','At the tip of the tail, at the end of the coccygeal vertebrae.','Tip of the coccygeal vertebrae.','Clears heat and restores consciousness.','{emergency,shock,heat stroke,diarrhoea,high fever}','Bleed with a 25G needle at the tail tip.','Avoid in bleeding disorders.'),
('WEI-GEN','On the dorsal midline at the tail base, in the space between the first and second coccygeal vertebrae.','Co1-Co2 interspace on the midline.','Regulates the tail and anus and raises yang caudally.','{weak tail,rectal prolapse,constipation,faecal incontinence,anal sac disease}','Perpendicular 0.5-1.5 cm.',null),
('LIU-FENG','In the interdigital grooves of the forepaw, dorsal surface — three points per limb (between digits 2-3, 3-4 and 4-5).','Interdigital grooves on the dorsal forepaw.','Clears damp-heat from the paw and reduces swelling and itching.','{pododermatitis,itchy paws,forelimb swelling,paw licking,atopic paws}','Shallow 0.2-0.5 cm, or a small bleed.','A sensitive area — the animal will usually pull the paw away.'),
('BA-FENG','In the interdigital grooves of the hindpaw, dorsal surface — three points per limb.','Interdigital grooves on the dorsal hindpaw.','Clears damp-heat from the hindpaw.','{pododermatitis,itchy paws,hindlimb swelling,paw licking}','Shallow 0.2-0.5 cm.',null)

) as v(code, loc, ana, fun, ind, ndl, cau)
where points.code = v.code;
