-- ======================================================================
-- เพิ่มจุดคลาสสิก 9 จุดที่เจ้าของเว็บเลือกจากจุดที่ใช้จริงในคลินิก
--   1 Tian-men · 4 Tai-yang · 11 Bi-tong · 12 Nao-shu · 25 Ding-chuan
--   34 Shen-shu-E · 35 Shen-peng · 62 Zhou-shu · 67 Jian-jiao
--
-- ตรวจเทียบ Xie's Veterinary Acupuncture (2007) บทที่ 6 โดยเปิดหน้าจริง
-- ของตำราอ่านยืนยันทุกจุด ไม่ได้ใช้ตัวแยกข้อความอย่างเดียว
-- ข้อความทั้งหมดเรียบเรียงขึ้นใหม่ ไม่ได้คัดลอกถ้อยคำจากตำรา
-- เลขในช่อง verified_source เป็นเลขกำกับรูปของบทที่ 6 ไม่ใช่รหัสจุดมาตรฐาน
-- ======================================================================

insert into points (
  code, slug, meridian_code, number,
  name_th, name_en, name_pinyin, name_zh,
  location_th, anatomy_th, location_en, anatomy_en,
  functions_th, functions_en, indications, indications_en, point_types,
  needle_th, needle_en, caution_th, caution_en,
  species, is_common, popularity, verified, verified_source
) values
  ('TIAN-MEN','tian-men','EX',null,
   'เทียนเหมิน','Tian Men (gate of heaven)','Tian Men','天门',
   'แนวกลางหลังของศีรษะ ระดับเดียวกับขอบท้ายของฐานใบหูทั้งสองข้าง',
   'แนวกลางศีรษะ ระดับขอบท้ายฐานใบหู',
   'On the dorsal midline of the head, level with the caudal rim of the two ear bases',
   'Dorsal midline of the head at the level of the caudal ear base',
   'จุดตัดของเส้นตู (GV) กับเส้นกระเพาะปัสสาวะ (BL) สงบจิตและปรับการทำงานของสมอง',
   'Crossing point of the GV and BL channels; calms the shen and regulates the brain',
   '{ชัก,ลมชัก,เสียงแหบ,เห่าไม่มีเสียง,เวียนศีรษะ,หัวเอียง,ปวดคอ}',
   '{seizures,epilepsy,dysphonia,loss of voice,vertigo,head tilt,cervical pain}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 0.3 cun','Perpendicular, 0.3 cun',
   'คนละจุดกับ DA-FENG-MEN ซึ่งอยู่ระดับขอบหน้าของฐานใบหู คลำขอบใบหูให้ชัดก่อนลงเข็ม',
   'A different point from DA-FENG-MEN, which lies level with the cranial rim of the ear bases - identify the ear margin before needling.',
   '{dog,cat}', true, 85, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 1)'),
  ('TAI-YANG','tai-yang','EX',null,
   'ไท่หยาง','Tai Yang (great yang)','Tai Yang','太阳',
   'ในแอ่งด้านข้างของศีรษะ ห่างจากหางตา (lateral canthus) ออกไปทางด้านข้าง 1 cun',
   'แอ่งด้านข้างศีรษะ ห่างหางตาออกข้าง 1 cun',
   'In a depression on the side of the head, 1 cun lateral to the lateral canthus of the eye',
   'Depression on the side of the head, 1 cun lateral to the lateral canthus',
   'ระบายความร้อนและลมที่ศีรษะ เปิดตา',
   'Clears heat and wind from the head; benefits the eyes',
   '{โรคตาเฉียบพลัน,ตาแดง,อัมพาตใบหน้า,ปวดหัว,ไข้,ลมร้อน}',
   '{acute ocular disorders,red eye,facial paralysis,headache,fever,wind heat}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 0.5-1 cun','Perpendicular, 0.5-1 cun',
   'อยู่ใกล้ลูกตา อย่าเอียงปลายเข็มเข้าหาเบ้าตา',
   'Close to the globe - never angle the needle toward the orbit.',
   '{dog,cat}', false, 60, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 4)'),
  ('BI-TONG','bi-tong','EX',null,
   'ปี๋ทง','Bi Tong (nose passing)','Bi Tong','鼻通',
   'ด้านข้างของจมูก กึ่งกลางระหว่าง LI-20 (อิ๋งเซียง) กับหัวตา (medial canthus)',
   'ข้างจมูก กึ่งกลางระหว่าง LI-20 กับหัวตา',
   'On the side of the nose, halfway between Ying-xiang (LI-20) and the medial canthus of the eye',
   'Side of the nose, midway between LI-20 and the medial canthus',
   'เปิดโพรงจมูก ระบายลมที่ใบหน้า',
   'Opens the nasal passages and dispels wind from the face',
   '{คัดจมูก,น้ำมูกไหล,ไซนัสอักเสบ,อัมพาตใบหน้า}',
   '{nasal congestion,nasal discharge,sinusitis,facial paralysis}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 0.3 cun','Perpendicular, 0.3 cun',
   null,
   null,
   '{dog,cat}', false, 60, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 11)'),
  ('NAO-SHU','nao-shu','EX',null,
   'เหน่าซู','Nao Shu (brain association point)','Nao Shu','脑俞',
   'เหนือกล้ามเนื้อ temporalis ที่ตำแหน่ง 1 ใน 3 ของเส้นลากจากขอบหน้าฐานใบหูไปยังหางตา',
   'เหนือกล้ามเนื้อ temporalis ที่ 1 ใน 3 จากฐานใบหูด้านหน้าไปหางตา',
   'Over the temporalis muscle, one third of the way along a line from the cranial ear base to the lateral canthus',
   'Over the temporalis muscle, one third from the cranial ear base toward the lateral canthus',
   'สงบจิต ปรับการทำงานของสมอง',
   'Calms the shen and regulates the brain',
   '{ชัก,ลมชัก,จิตใจไม่สงบ,กระวนกระวาย}',
   '{seizures,epilepsy,shen disturbance,restlessness}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 0.3 cun','Perpendicular, 0.3 cun',
   null,
   null,
   '{dog,cat}', false, 60, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 12)'),
  ('DING-CHUAN','ding-chuan','EX',null,
   'ติ้งฉวน','Ding Chuan (stop cough / asthma)','Ding Chuan','定喘',
   'ด้านบนค่อนข้าง ที่รอยต่อคอกับอก ห่างจาก GV-14 (ต้าจุย บนแนวกลางระหว่าง C7 กับ T1) ออกข้าง 0.5 cun',
   'รอยต่อคอ-อก ห่างจาก GV-14 ออกข้าง 0.5 cun',
   'On the dorsolateral cervicothoracic junction, 0.5 cun lateral to Da-zhui (GV-14, on the midline between C7 and T1)',
   'Cervicothoracic junction, 0.5 cun lateral to GV-14',
   'ระงับไอ ผ่อนการหายใจ ปรับลมปราณปอด',
   'Stops cough, eases the breathing and regulates lung qi',
   '{ไอ,หอบ,หายใจลำบาก,หืด}',
   '{cough,asthma,dyspnea,wheezing}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉากหรือเฉียง ลึกราว 0.5 cun','Perpendicular or oblique, 0.5 cun',
   'อยู่เหนือช่องอกส่วนหน้า อย่าแทงตั้งฉากลึกเกินกำหนด เสี่ยงปอดรั่ว',
   'Overlies the cranial thorax - do not exceed the stated depth on a perpendicular insertion; risk of pneumothorax.',
   '{dog,cat}', false, 60, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 25)'),
  ('SHEN-SHU-E','shen-shu-e','EX',null,
   'เซิ่นซู (ฉบับม้า)','Shen Shu-E (kidney association, equine)','Shen Shu','肾俞',
   'ด้านบนค่อนข้างของบริเวณเอว-กระเบนเหน็บ ห่างจาก BAI-HUI (แนวกลาง L7-S1) ออกข้าง 1.5 cun',
   'เอว-กระเบนเหน็บ ห่างจาก BAI-HUI ออกข้าง 1.5 cun',
   'On the dorsolateral lumbosacral region, 1.5 cun lateral to Bai-hui (the L7-S1 dorsal midline)',
   'Dorsolateral lumbosacral region, 1.5 cun lateral to Bai-hui',
   'บำรุงไต เสริมลมปราณและอินของไต',
   'Tonifies the Kidney; supplements Kidney qi and yin',
   '{ไตเสื่อม,ไตวาย,ลมปราณไตพร่อง,อินไตพร่อง,หูหนวก,ปัสสาวะเล็ด,บวมน้ำ,ปวดหลังช่วงอกและเอว}',
   '{chronic kidney disease,renal failure,Kidney qi deficiency,Kidney yin deficiency,deafness,urinary incontinence,edema,thoracolumbar pain}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 0.5 cun','Perpendicular, 0.5 cun',
   'คนละจุดกับ BL-23 (เซิ่นซูฉบับคน) ที่อยู่สูงขึ้นไปในบริเวณเอว ตำราระบุชัดว่าจุดนี้แปลงตำแหน่งมาจากม้า',
   'A different point from BL-23 (the human transposition), which lies further cranial in the lumbar region. The text states this one is transposed from the equine.',
   '{dog,cat}', false, 60, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 34)'),
  ('SHEN-PENG','shen-peng','EX',null,
   'เซิ่นเผิง','Shen Peng (kidney shelf)','Shen Peng','肾棚',
   'ด้านบนค่อนข้างของเอวตอนท้าย ห่างจาก SHEN-SHU-E ไปทางหัว 1.5 cun',
   'เอวตอนท้าย ห่างจาก SHEN-SHU-E ไปทางหัว 1.5 cun',
   'On the dorsolateral caudal lumbar region, 1.5 cun cranial to Shen-shu-E',
   'Caudal lumbar region, 1.5 cun cranial to Shen-shu-E',
   'อุ่นหยาง บำรุงไต คลายปวดบริเวณเอวและกระเบนเหน็บ',
   'Warms yang, tonifies the Kidney and relieves lumbosacral pain',
   '{หยางพร่อง,ขาหลังอ่อนแรง,ขาหลังเป็นอัมพาต,ปวดเอวและกระเบนเหน็บ,หมอนรองกระดูกเอว-กระเบนเหน็บ,ปวดข้อสะโพก,ปวดท้อง,ท้องเสีย}',
   '{yang deficiency,pelvic limb weakness,pelvic limb paralysis,lumbosacral pain,lumbosacral intervertebral disk disease,coxofemoral joint pain,abdominal pain,diarrhea}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 0.5 cun','Perpendicular, 0.5 cun',
   null,
   null,
   '{dog,cat}', false, 35, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 35)'),
  ('ZHOU-SHU','zhou-shu','EX',null,
   'โจ่วซู','Zhou Shu (elbow association point)','Zhou Shu','肘俞',
   'ด้านนอกของข้อศอก ระหว่างปุ่ม lateral tuberosity ของกระดูก humerus กับปลาย olecranon',
   'ด้านนอกข้อศอก ระหว่าง lateral tuberosity ของ humerus กับ olecranon',
   'On the lateral side of the elbow, between the lateral tuberosity of the humerus and the olecranon',
   'Lateral elbow, between the lateral humeral tuberosity and the olecranon',
   'คลายข้อศอก เดินลมปราณขาหน้า',
   'Frees the elbow joint and moves qi in the thoracic limb',
   '{ข้อศอกเสื่อม,ข้อศอกอักเสบ,ขาหน้าเดินกะเผลก,ขาหน้าเป็นอัมพาต}',
   '{elbow osteoarthritis,elbow pain,thoracic limb lameness,thoracic limb paralysis}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 0.5 cun','Perpendicular, 0.5 cun',
   null,
   null,
   '{dog,cat}', false, 60, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 62)'),
  ('JIAN-JIAO','jian-jiao','EX',null,
   'เจี้ยนเจี่ยว','Jian Jiao (coxa angle)','Jian Jiao','荐角',
   'ด้านบนค่อนข้างของสะโพก ในแอ่งที่อยู่ใต้ต่อปุ่มกระดูกเชิงกรานด้านหน้าบน (cranial dorsal iliac spine)',
   'แอ่งใต้ต่อ cranial dorsal iliac spine ด้านบนค่อนข้างของสะโพก',
   'On the dorsolateral aspect of the hip, in a depression just ventral to the cranial dorsal iliac spine',
   'Dorsolateral hip, depression just ventral to the cranial dorsal iliac spine',
   'คลายข้อสะโพก เดินลมปราณขาหลัง',
   'Frees the coxofemoral joint and moves qi in the pelvic limb',
   '{ข้อสะโพกเสื่อม,ปวดสะโพก,ข้อสะโพกเจริญผิดปกติ,ขาหลังเดินกะเผลก,ขาหลังอ่อนแรง,ขาหลังเป็นอัมพาต}',
   '{coxofemoral osteoarthritis,hip pain,hip dysplasia,pelvic limb lameness,pelvic limb weakness,pelvic limb paralysis}',
   '{จุดคลาสสิกในสัตว์}',
   'ตั้งฉาก ลึกราว 1-1.5 cun','Perpendicular, 1-1.5 cun',
   null,
   null,
   '{dog,cat}', true, 85, true, 'Xie''s Veterinary Acupuncture (2007) ch.6 (fig. ref 67)')
on conflict (code) do update set
  slug = excluded.slug, name_th = excluded.name_th, name_en = excluded.name_en,
  name_pinyin = excluded.name_pinyin, name_zh = excluded.name_zh,
  location_th = excluded.location_th, anatomy_th = excluded.anatomy_th,
  location_en = excluded.location_en, anatomy_en = excluded.anatomy_en,
  functions_th = excluded.functions_th, functions_en = excluded.functions_en,
  indications = excluded.indications, indications_en = excluded.indications_en,
  point_types = excluded.point_types,
  needle_th = excluded.needle_th, needle_en = excluded.needle_en,
  caution_th = excluded.caution_th, caution_en = excluded.caution_en,
  species = excluded.species, is_common = excluded.is_common,
  popularity = excluded.popularity, verified = excluded.verified,
  verified_source = excluded.verified_source;

-- ---------- จับคู่อาการ ----------
insert into condition_points (condition_id, point_id, role, note_th, sort_order)
select c.id, p.id, v.role, nullif(v.note,''), v.ord
from (values
  ('epilepsy','TIAN-MEN','primary','จุดตัด GV กับ BL บนแนวกลางศีรษะ',9),
  ('epilepsy','NAO-SHU','secondary','คู่กับ TIAN-MEN ในรายชักซ้ำ',10),
  ('neck-pain','TIAN-MEN','secondary','',9),
  ('anxiety','NAO-SHU','secondary','ใช้เมื่อมีอาการทางจิตประสาทร่วม',9),
  ('facial-paralysis','TAI-YANG','secondary','ครอบคลุมอาการทางตาที่มาด้วยกัน',9),
  ('facial-paralysis','BI-TONG','secondary','เน้นด้านจมูก',10),
  ('cough','DING-CHUAN','primary','จุดเฉพาะของอาการไอและหอบ',9),
  ('ckd','SHEN-SHU-E','primary','เซิ่นซูฉบับม้า คนละจุดกับ BL-23',9),
  ('incontinence','SHEN-SHU-E','primary','',9),
  ('hindlimb-paresis','SHEN-PENG','secondary','',9),
  ('ivdd','SHEN-PENG','secondary','เน้นรอยโรคช่วงเอว-กระเบนเหน็บ',9),
  ('osteoarthritis','ZHOU-SHU','secondary','เฉพาะข้อศอก',9),
  ('osteoarthritis','JIAN-JIAO','primary','เฉพาะข้อสะโพก',10),
  ('hip-dysplasia','JIAN-JIAO','primary','คลำ cranial dorsal iliac spine เป็นหลัก',9)
) as v(cslug, pcode, role, note, ord)
join conditions c on c.slug = v.cslug
join points     p on p.code = v.pcode
on conflict (condition_id, point_id) do update set
  role = excluded.role, note_th = excluded.note_th, sort_order = excluded.sort_order;

-- ---------- ตรวจผล ----------
select code, name_th, name_zh, is_common, popularity
from points
where code in ('TIAN-MEN','TAI-YANG','BI-TONG','NAO-SHU','DING-CHUAN',
               'SHEN-SHU-E','SHEN-PENG','ZHOU-SHU','JIAN-JIAO')
order by popularity desc, code;

select count(*) as จุดคลาสสิกทั้งหมด from points where meridian_code = 'EX';
