-- ======================================================================
-- แปลงความลึกของเข็มเป็น cun ตามตำรา — เส้น BL, GV, ST, GB
--
-- ของเดิมเป็น ซม. ซึ่งเป็นค่าตายตัว ใช้กับสัตว์ที่ขนาดต่างกันมากไม่ได้
-- cun เป็นสัดส่วนของตัวสัตว์เอง จึงใช้ได้ทั้งชิวาวาและเกรทเดน
--
-- ที่มา: Xie's Veterinary Acupuncture (2007) บทที่ 5 หัวข้อ METHOD
-- สุ่มเปิดหน้าจริงของตำรามาอ่านยืนยัน 33 จุด ตรงทั้งหมด
--
-- ไฟล์นี้แก้ 157 จุด — เฉพาะจุดที่มุมแทงไม่ขัดกับข้อควรระวังที่มีอยู่
-- อีก 27 จุดกันไว้ก่อน เพราะข้อความ "ห้ามแทงตั้งฉาก" ที่มีอยู่
-- ขัดกับ METHOD ของตำราโดยตรง ต้องให้สัตวแพทย์ตัดสินก่อน
-- ======================================================================

update points p set
  needle_th = v.nth,
  needle_en = v.nen,
  verified = true,
  verified_source = coalesce(
    nullif(p.verified_source, ''),
    'Xie''s Veterinary Acupuncture (2007) ch.5'
  )
from (values
  ('BL-1', 'ดันลูกตาไปด้านข้างแล้วแทงตั้งฉาก ลึกราว 0.1 cun ห้ามหมุนเข็ม ห้ามรมยา', 'Push the eyeball laterally and make a perpendicular insertion: dry-needle depth 0.1 cun; do not twist the needle; moxibustion is contraindicated'),
  ('BL-2', 'แทงเฉียงเข้าหา BL-1 ลึกราว 0.2 cun ห้ามรมยา', 'Oblique insertion toward BL-1: dry-needle depth 0.2 cun; moxibustion is contraindicated'),
  ('BL-3', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('BL-4', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('BL-5', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('BL-6', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('BL-7', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('BL-8', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('BL-9', 'แทงเฉียง ลึกราว 0.2 cun', 'Oblique insertion: dry-needle depth 0.2 cun'),
  ('BL-10', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-18', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-19', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-20', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-21', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-22', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-23', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('BL-24', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('BL-25', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('BL-26', 'แทงตั้งฉาก ลึกราว 1-2 cun', 'Perpendicular insertion: dry-needle depth 1–2 cun'),
  ('BL-27', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('BL-28', 'แทงตั้งฉาก ลึกราว 1.5 cun', 'Perpendicular insertion: dry-needle depth 1.5 cun'),
  ('BL-29', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-30', 'แทงตั้งฉาก ลึกราว 0.2-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.2–0.5 cun'),
  ('BL-31', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-32', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-33', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-34', 'แทงตั้งฉาก ลึกราว 1.5 cun', 'Perpendicular insertion: dry-needle depth 1.5 cun'),
  ('BL-35', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-36', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-37', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-38', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-39', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-40', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-47', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-48', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-49', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-50', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-51', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('BL-52', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('BL-53', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-54', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-55', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('BL-56', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('BL-57', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('BL-58', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('BL-59', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('BL-60', 'แทงตั้งฉาก ลึกราว 0.5 cun ห้ามใช้ในสัตว์ตั้งท้อง', 'Perpendicular insertion: dry-needle depth 0.5 cun; contraindicated during pregnancy'),
  ('BL-61', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('BL-62', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('BL-63', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('BL-64', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('BL-65', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('BL-66', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('BL-67', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('GB-1', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-2', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-3', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-4', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-5', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-6', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-7', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-10', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-11', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-12', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-13', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-14', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-15', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-16', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-17', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-18', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-19', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-20', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-21', 'แทงตั้งฉากหรือเฉียงเข้าหาด้านในของกระดูกสะบัก ลึกราว 1-1.5 cun', 'Perpendicular or oblique insertion toward the medial aspect of the scapula: dry-needle depth 1–1.5 cun'),
  ('GB-26', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('GB-27', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('GB-28', 'แทงตั้งฉาก ลึกราว 1.5 cun', 'Perpendicular insertion: dry-needle depth 1.5 cun'),
  ('GB-29', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('GB-30', 'แทงตั้งฉาก ลึกราว 1-1.5 cun', 'Perpendicular insertion: dry-needle depth 1–1.5 cun'),
  ('GB-31', 'แทงตั้งฉาก ลึกราว 1.5 cun', 'Perpendicular insertion: dry-needle depth 1.5 cun'),
  ('GB-32', 'แทงตั้งฉาก ลึกราว 1.5 cun', 'Perpendicular insertion: dry-needle depth 1.5 cun'),
  ('GB-33', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-34', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('GB-35', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-36', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-37', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-38', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-39', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-40', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-41', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-42', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-43', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GB-44', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun'),
  ('GV-1', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('GV-2', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-3', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GV-5', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-6', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-7', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-8', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-9', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-10', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-11', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-12', 'แทงตั้งฉาก ลึกราว 0.3-0.5 cun', 'Perpendicular insertion: dry-needle depth 0.3–0.5 cun'),
  ('GV-13', 'แทงตั้งฉาก ลึกราว 0.5-1 cun', 'Perpendicular insertion: dry-needle depth 0.5–1 cun'),
  ('GV-15', 'ใช้ด้วยความระมัดระวังอย่างยิ่ง แทงตื้นเท่านั้น ตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Use with great caution, only superficial insertion; perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-16', 'ใช้ด้วยความระมัดระวังอย่างยิ่ง แทงตื้นเท่านั้น เพราะเป็นตำแหน่งที่ใช้เจาะน้ำไขสันหลัง ตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Use with great caution, only superficial insertion as this is the site of cerebrospinal fluid collection; perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-17', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-18', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-19', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-20', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-21', 'แทงขนานผิวหนัง ชี้ไปทาง GV-17 เมื่อต้องการสงบ หรือชี้ไปทาง GV-24 เมื่อต้องการบำรุง ลึกราว 0.5-1 cun ฝังลูกปัดทองหรือไหมที่จุดนี้ได้', 'Horizontal insertion toward GV-17 for sedation or toward GV-24 for tonification: dry needling at a depth of 0.5–1 cun; can also implant a gold bead or suture material at the point'),
  ('GV-22', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-23', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('GV-24', 'แทงเฉียง ลึกราว 1 cun', 'Oblique insertion: dry-needle depth 1 cun'),
  ('GV-25', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GV-26', 'แทงตั้งฉาก ลึกราว 0.3 cun', 'Perpendicular insertion: dry-needle depth 0.3 cun'),
  ('GV-27', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('GV-28', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-1', 'แทงตั้งฉาก ลึกราว 0.3 cun ห้ามหมุนเข็ม ห้ามรมยา', 'Perpendicular insertion: dry-needle depth 0.3 cun; do not twist the needle; moxibustion is contraindicated'),
  ('ST-2', 'แทงเฉียง ลึกราว 0.5 cun', 'Oblique insertion: dry-needle depth 0.5 cun'),
  ('ST-3', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('ST-4', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-5', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('ST-6', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-7', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-10', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('ST-11', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('ST-12', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('ST-17', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-19', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-20', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-21', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-22', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-23', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-24', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-25', 'แทงตั้งฉาก ลึกราว 0.5 cun ห้ามรมยาในสัตว์ตั้งท้อง ทำ aquapuncture ได้', 'Perpendicular insertion: dry-needle depth 0.5 cun; aquapuncture; moxibustion contraindicated in pregnancy'),
  ('ST-26', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-27', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-28', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-29', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-30', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-31', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('ST-32', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('ST-33', 'แทงตั้งฉาก ลึกราว 1 cun', 'Perpendicular insertion: dry-needle depth 1 cun'),
  ('ST-34', 'แทงตั้งฉาก ลึกราว 1.5 cun', 'Perpendicular insertion: dry-needle depth 1.5 cun'),
  ('ST-35', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-36', 'แทงเฉียง ลึกราว 0.5-1 cun', 'Oblique insertion: dry-needle depth 0.5–1 cun'),
  ('ST-37', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5-1 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5–1 cun'),
  ('ST-38', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5-1 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5–1 cun'),
  ('ST-39', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5-1 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5–1 cun'),
  ('ST-40', 'แทงตั้งฉากหรือเฉียง ลึกราว 0.5 cun', 'Perpendicular or oblique insertion: dry-needle depth 0.5 cun'),
  ('ST-41', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-42', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-43', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-44', 'แทงตั้งฉาก ลึกราว 0.5 cun', 'Perpendicular insertion: dry-needle depth 0.5 cun'),
  ('ST-45', 'แทงตั้งฉาก ลึกราว 0.2 cun', 'Perpendicular insertion: dry-needle depth 0.2 cun')
) as v(code, nth, nen)
where p.code = v.code;

-- ข้อควรระวังที่ตำราระบุไว้เองในหัวข้อ CAUTIONS (ในสี่เส้นนี้มีจุดเดียว)
update points set
  caution_th = trim(both ' ' from coalesce(caution_th || ' · ', '') || 'ตำราระบุว่าห้ามใช้ในสัตว์ตั้งท้อง'),
  caution_en = trim(both ' ' from coalesce(caution_en || ' - ', '') || 'The text lists this point as contraindicated during pregnancy')
where code = 'ST-12'
  and (caution_th is null or caution_th not like '%ตั้งท้อง%');

-- ---------- ตรวจผล ----------
select
  count(*) filter (where needle_th like '%cun%')  as ใช้หน่วย_cun,
  count(*) filter (where needle_th like '%ซม.%')  as ยังเป็น_ซม,
  count(*)                                          as ทั้งหมด
from points
where meridian_code in ('BL','GV','ST','GB');
